version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: its-ng1
    ports:
      - "80:80"
    networks:
      - training-network

  zookeeper:
    image: zookeeper:latest
    container_name: its-zk1
    ports:
      - "2181:2181"
    networks:
      - training-network

  kafka:
    image: bitnami/kafka:latest
    container_name: its-kf1
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: its-zk1:2181
      KAFKA_CREATE_TOPICS: "training-topic"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - training-network

  # java-app:
  #   build: ./Java/
  #   # depends_on:
  #   #   - kafka
  #   networks:
  #     - training-network

networks:
  training-network:
    driver: bridge