version: '3.8'

name: its

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - training-network

  kafka:
    image: bitnami/kafka:latest
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "training-topic:1:1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - training-network

  # java-app:
  #   build: ./Java/
  #   depends_on:
  #     - kafka
  #   networks:
  #     - training-network

networks:
  training-network:
    driver: bridge