version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: its-p1-ng1
    ports:
      - "80:80"
    # volumes:
    #   - ./FE/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - its-p1-net

  nodejs:
    build:
      context: ./BE
      dockerfile: Dockerfile.nodejs
    container_name: its-p1-nj1
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - its-p1-net

  db:
    image: mysql:latest
    container_name: its-p1-db1
    volumes:
      - ./DB/DB_DATA:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: its_db
      MYSQL_AUTH_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - its-p1-net

networks:
  its-p1-net:
    driver: bridge
