apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset2
  labels:
    app: my-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
      - name: my-container2
        image: nginx:latest
        ports:
        - containerPort: 8080
